=== AlexSh-l/XMLXSD_Parsing/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.task3.com/tourist-vouchers"
        xmlns:c="http://www.task3.com/tourist-vouchers">

    <complexType name="cost">
        <sequence>
            <element name="cost" type="double"/>
            <element name="includes" type="string" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <simpleType name="voucher-type">
        <restriction base="string">
            <enumeration value="Packet_tour"/>
            <enumeration value="Individual_tour"/>
            <enumeration value="Burning_tour"/>
            <enumeration value="Excursion_tour"/>
            <enumeration value="Sport_tour"/>
            <enumeration value="Cruise"/>
            <enumeration value="Hiking_trip"/>
            <enumeration value="Shop_tour"/>
        </restriction>
    </simpleType>

    <simpleType name="food-type">
        <restriction base="string">
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="FB"/>
            <enumeration value="AI"/>
            <enumeration value="UAI"/>
        </restriction>
    </simpleType>

    <simpleType name="room-type">
        <restriction base="int">
            <enumeration value="1"/>
            <enumeration value="2"/>
            <enumeration value="3"/>
            <enumeration value="4"/>
            <enumeration value="5"/>
        </restriction>
    </simpleType>

    <simpleType name="star-type">
        <restriction base="int">
            <enumeration value="1"/>
            <enumeration value="2"/>
            <enumeration value="3"/>
            <enumeration value="4"/>
            <enumeration value="5"/>
        </restriction>
    </simpleType>

    <complexType name="hotel">
        <sequence>
            <element name="stars" type="c:star-type"/>
            <element name="is-food-included" type="boolean"/>
            <element name="food" type="c:food-type" minOccurs="0"/>
            <element name="amount-of-rooms" type="c:room-type"/>
            <element name="is-tv-included" type="boolean"/>
            <element name="is-conditioner-included" type="boolean"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>

    <complexType name="voucher" abstract="true">
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" use="optional"/>
    </complexType>

    <element name="tourist-voucher">
        <complexType>
            <complexContent>
                <extension base="c:voucher">
                    <sequence>
                        <element name="Voucher-type" type="c:voucher-type"/>
                        <element name="Country" type="string" maxOccurs="unbounded"/>
                        <element name="Number-days" type="int"/>
                        <element name="Number-nights" type="int"/>
                        <element name="Start-date" type="dateTime"/>
                        <element name="Transport" type="string" maxOccurs="unbounded"/>
                        <element name="Hotel" type="c:hotel" maxOccurs="unbounded"/>
                        <element name="Cost" type="c:cost" maxOccurs="unbounded"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="TouristVouchers">
        <complexType>
            <sequence>
                <element ref="c:tourist-voucher" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

</schema>

=== AlexSh-l/XMLXSD_Parsing/data/tourist-vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:TouristVouchers
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:c="http://www.task3.com/tourist-vouchers"
        xsi:schemaLocation="http://www.task3.com/tourist-vouchers schema.xsd">

    <c:tourist-voucher id="ID-1235469875">
        <Voucher-type>Packet_tour</Voucher-type>
        <Country>Мексика</Country>
        <Number-days>2</Number-days>
        <Number-nights>2</Number-nights>
        <Start-date>2022-07-10T11:00:00</Start-date>
        <Transport>Самолёт</Transport>
        <Transport>Автобус</Transport>
        <Hotel>
            <name>BellaVingtol</name>
            <stars>5</stars>
            <is-food-included>true</is-food-included>
            <food>UAI</food>
            <amount-of-rooms>2</amount-of-rooms>
            <is-tv-included>true</is-tv-included>
            <is-conditioner-included>true</is-conditioner-included>
        </Hotel>
        <Cost>
            <cost>2000.25</cost>
            <includes>Проживание в отеле</includes>
            <includes>Поездка от аэропорта</includes>
        </Cost>
    </c:tourist-voucher>

    <c:tourist-voucher id="ID-1343">
        <Voucher-type>Shop_tour</Voucher-type>
        <Country>Германия</Country>
        <Number-days>10</Number-days>
        <Number-nights>9</Number-nights>
        <Start-date>2021-12-21T20:30:00</Start-date>
        <Transport>Автобус</Transport>
        <Hotel>
            <name>Grettenburg</name>
            <stars>3</stars>
            <is-food-included>false</is-food-included>
            <amount-of-rooms>1</amount-of-rooms>
            <is-tv-included>true</is-tv-included>
            <is-conditioner-included>false</is-conditioner-included>
        </Hotel>
        <Cost>
            <cost>500.0</cost>
            <includes>Проживание в отеле</includes>
            <includes>Поездка на автобусе</includes>
        </Cost>
    </c:tourist-voucher>

    <c:tourist-voucher id="ID-567">
        <Voucher-type>Cruise</Voucher-type>
        <Country>Норвегия</Country>
        <Country>Швеция</Country>
        <Country>Италия</Country>
        <Number-days>31</Number-days>
        <Number-nights>32</Number-nights>
        <Start-date>2022-08-01T13:30:00</Start-date>
        <Transport>Автобус</Transport>
        <Transport>Паром</Transport>
        <Transport>Круизный лайнер</Transport>
        <Hotel>
            <name>Stratus</name>
            <stars>5</stars>
            <is-food-included>true</is-food-included>
            <food>UAI</food>
            <amount-of-rooms>5</amount-of-rooms>
            <is-tv-included>true</is-tv-included>
            <is-conditioner-included>true</is-conditioner-included>
        </Hotel>
        <Hotel>
            <name>Laint</name>
            <stars>5</stars>
            <is-food-included>true</is-food-included>
            <food>BB</food>
            <amount-of-rooms>3</amount-of-rooms>
            <is-tv-included>true</is-tv-included>
            <is-conditioner-included>false</is-conditioner-included>
        </Hotel>
        <Cost>
            <cost>5000.0</cost>
            <includes>Билеты на круизный лайнер</includes>
            <includes>Поездка на автобусе</includes>
            <includes>Поездка на пароме</includes>
            <includes>Проживание в отеле</includes>
        </Cost>
    </c:tourist-voucher>
</c:TouristVouchers>
